#### Python Lists
- float - real number
- int - integer number
- str - string, text
- bool - True, False

In [1]:
fam = [1.73, 1.68, 1.71, 1.89]
fam

[1.73, 1.68, 1.71, 1.89]

In [ ]:
fam = ["liz", 1.73]

In [2]:
height = [1.73, 1.68, 1.171, 1.89, 1.79]
height

[1.73, 1.68, 1.171, 1.89, 1.79]

In [3]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [4]:
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

##### Solution: NumPy

In [9]:
import numpy as np

np_height = np.array(height)
np_height

array([1.73 , 1.68 , 1.171, 1.89 , 1.79 ])

In [10]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [12]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 46.38134362, 24.7473475 , 21.44127836])

In [13]:
np.array([1.0, "is", True])

array(['1.0', 'is', 'True'], dtype='<U32')

In [15]:
python_list = [1, 2, 3]
numpy_array = np.array(python_list)

In [16]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [17]:
numpy_array + numpy_array

array([2, 4, 6])

In [18]:
bmi

array([21.85171573, 20.97505669, 46.38134362, 24.7473475 , 21.44127836])

In [19]:
bmi[1]

np.float64(20.97505668934241)

In [20]:
bmi[bmi > 23]

array([46.38134362, 24.7473475 ])

In [26]:
np_2d = np.array([height, weight])
np_2d

array([[ 1.73 ,  1.68 ,  1.171,  1.89 ,  1.79 ],
       [65.4  , 59.2  , 63.6  , 88.4  , 68.7  ]])

In [27]:
np_2d.shape

(2, 5)

In [28]:
np_2d[0][2]

np.float64(1.171)

In [29]:
np_2d[0, 2]

np.float64(1.171)

In [30]:
np_2d[:, 1:3]

array([[ 1.68 ,  1.171],
       [59.2  , 63.6  ]])

In [31]:
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [32]:
np_2d[:, 1]

array([ 1.68, 59.2 ])

In [35]:
np.mean(np_height)

np.float64(1.6522)

In [36]:
np.median(np_height)

np.float64(1.73)

In [37]:
np.std(np_height)

np.float64(0.25056607910888495)

In [38]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [39]:
np_bmi = np.array([height, weight])

In [40]:
np.mean(np_bmi[:, 0])

np.float64(38.33)

In [41]:
np.mean(np_bmi[:, 1])

np.float64(56.985)

In [42]:
np.median(np_bmi[:, 0])

np.float64(38.33)

In [43]:
np.median(np_bmi[:, 1])

np.float64(56.985)

In [44]:
np.std(np_bmi[:, 0])

np.float64(36.47)

In [45]:
np.std(np_bmi[:, 1])

np.float64(55.235)

In [46]:
np.corrcoef(np_bmi[:, 0], np_bmi[:, 1])

array([[1., 1.],
       [1., 1.]])

In [48]:
np_city = np.column_stack((height, weight))
np_city

array([[  1.86,  74.8 ],
       [  1.75, 112.22],
       [  1.81,  22.27],
       ...,
       [  2.07,  79.04],
       [  1.72,  68.48],
       [  1.82,  52.25]], shape=(5000, 2))